# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 186444126+zoror2@users.noreply.github.com.
author_name: Prajwal H M
contract_name: aml_registry
deployment_language: python
preset_name: production
project_name: aml-registry-contracts

