# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: 186444126+zoror2@users.noreply.github.com.
author_name: Prajwal H M
cloud_provider: vercel
contract_name: aml_registry
deployment_language: python
preset_name: production
project_name: aml-registry

